name: Continuous integration
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Build ubuntu
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ghc: ['9.0.1']
        cabal: ['3.6.2.0']

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: haskell/actions/setup@v1.2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal v2-update
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - name: Build
        run: |
          cabal build
          cabal exec kzhang build
          touch _site/.nojekyll
          echo kzhang.org > _site/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: dev
          force_orphan: true